# Cartographoor Production Configuration

# Logging configuration
logging:
  level: info

# Run once and exit
runOnce: true

# Discovery configuration
discovery:
  # Discovery interval (default: 1h)
  interval: 1h

  # Static network configuration
  static:
    networks:
      - name: mainnet
        description: Production Ethereum network
        chainId: 1
        genesisTime: 1606824023
        genesisDelay: 604800
        configUrl: "https://raw.githubusercontent.com/eth-clients/mainnet/refs/heads/main/metadata/config.yaml"
        serviceUrls:
          ethstats: https://ethstats.mainnet.ethpandaops.io
          forkmon: https://forkmon.mainnet.ethpandaops.io
          blobArchive: https://blob-archive.mainnet.ethpandaops.io
          forky: https://forky.mainnet.ethpandaops.io
          tracoor: https://tracoor.mainnet.ethpandaops.io
        forks:
          consensus:
            electra:
              epoch: 364032
              minClientVersions:
                grandine: "1.1.0"
                lighthouse: "7.0.0"
                lodestar: "1.29.0"
                nimbus: "25.4.1"
                prysm: "6.0.0"
                teku: "25.4.1"

      - name: sepolia
        description: Smaller testnet for application development with controlled validator set.
        chainId: 11155111
        genesisTime: 1655647200
        genesisDelay: 86400
        configUrl: "https://raw.githubusercontent.com/eth-clients/sepolia/refs/heads/main/metadata/config.yaml"
        serviceUrls:
          dora: https://dora.sepolia.ethpandaops.io
          beaconExplorer: https://dora.sepolia.ethpandaops.io
          checkpointSync: https://checkpoint-sync.sepolia.ethpandaops.io
          ethstats: https://ethstats.sepolia.ethpandaops.io
          forkmon: https://forkmon.sepolia.ethpandaops.io
          blobArchive: https://blob-archive.sepolia.ethpandaops.io
          forky: https://forky.sepolia.ethpandaops.io
          tracoor: https://tracoor.sepolia.ethpandaops.io
        forks:
          consensus:
            electra:
              epoch: 222464
              minClientVersions:
                grandine: "1.0.0"
                lighthouse: "7.0.0-beta.0"
                lodestar: "1.27.0"
                nimbus: "25.2.0"
                prysm: "5.3.0"
                teku: "25.2.0"
            fusaka:
              epoch: 272640
              minClientVersions:
                grandine: "2.0.0.rc0"
                lighthouse: "8.0.0-rc.0"
                lodestar: "1.35.0-rc.1"
                nimbus: "25.9.2"
                prysm: "6.1.0"
                teku: "25.9.3"
                tysm: "0.43.0"

      - name: holesky
        description: Long-term public testnet designed for staking/validator testing with high validator counts.
        chainId: 17000
        genesisTime: 1695902100
        genesisDelay: 300
        configUrl: "https://raw.githubusercontent.com/eth-clients/holesky/refs/heads/main/metadata/config.yaml"
        serviceUrls:
          dora: https://dora.holesky.ethpandaops.io
          beaconExplorer: https://dora.holesky.ethpandaops.io
          checkpointSync: https://checkpoint-sync.holesky.ethpandaops.io
          ethstats: https://ethstats.holesky.ethpandaops.io
          forkmon: https://forkmon.holesky.ethpandaops.io
          blobArchive: https://blob-archive.holesky.ethpandaops.io
          forky: https://forky.holesky.ethpandaops.io
          tracoor: https://tracoor.holesky.ethpandaops.io
        forks:
          consensus:
            electra:
              epoch: 115968
              minClientVersions:
                grandine: "1.0.0"
                lighthouse: "7.0.0-beta.0"
                lodestar: "1.27.0"
                nimbus: "25.2.0"
                prysm: "5.3.0"
                teku: "25.2.0"
            fusaka:
              epoch: 165120
              minClientVersions:
                grandine: "2.0.0.rc0"
                lighthouse: "8.0.0-rc.0"
                lodestar: "1.35.0-rc.1"
                nimbus: "25.9.2"
                prysm: "6.1.0"
                teku: "25.9.3"
                tysm: "0.43.0"

      - name: hoodi
        description: New public testnet (launched March 2025) designed for validator testing and protocol upgrades, replacing Holesky.
        chainId: 560048
        genesisTime: 1742212800
        genesisDelay: 600
        configUrl: "https://raw.githubusercontent.com/eth-clients/hoodi/refs/heads/main/metadata/config.yaml"
        serviceUrls:
          dora: https://dora.hoodi.ethpandaops.io
          beaconExplorer: https://dora.hoodi.ethpandaops.io
          checkpointSync: https://checkpoint-sync.hoodi.ethpandaops.io
          forkmon: https://forkmon.hoodi.ethpandaops.io
          forky: https://forky.hoodi.ethpandaops.io
          tracoor: https://tracoor.hoodi.ethpandaops.io
        forks:
          consensus:
            electra:
              epoch: 2048
              minClientVersions:
                grandine: "1.0.0"
                lighthouse: "7.0.0-beta.0"
                lodestar: "1.27.0"
                nimbus: "25.2.0"
                prysm: "5.3.0"
                teku: "25.2.0"
            fusaka:
              epoch: 50688
              minClientVersions:
                grandine: "2.0.0.rc0"
                lighthouse: "8.0.0-rc.0"
                lodestar: "1.35.0-rc.1"
                nimbus: "25.9.2"
                prysm: "6.1.0"
                teku: "25.9.3"
                tysm: "0.43.0"

  # GitHub discovery configuration
  github:
    # List of repositories to check for networks
    repositories:
#      - name: ethpandaops/bal-devnets
#        namePrefix: bal-
#        displayName: BAL Devnets
#        description: "Block‑Level Access Lists (BAL) embed every account and storage slot touched during a block—with their post‑execution values—to unlock parallel disk reads, parallel validation, and stateless state updates."
#        image: https://ethpandaops.io/img/bal.jpg
#        links:
#          - title: "EIP-7928: Block-Level Access Lists"
#            url: "https://eips.ethereum.org/EIPS/eip-7928"
#          - title: "Eth Magicians"
#            url: "https://ethereum-magicians.org/t/eip-7928-block-level-access-lists/23337"
#      - name: ethpandaops/epbs-devnets
#        namePrefix: epbs-
#        displayName: ePBS Devnets
#        description: "Enshrined Proposer‑Builder Separation (ePBS) splits Ethereum blocks into consensus and execution layers and lets the consensus proposer pick the execution proposer directly."
#        image: https://ethpandaops.io/img/epbs.jpg
#        links:
#          - title: "EIP-7732: Enshrined Proposer-Builder Separation"
#            url: "https://eips.ethereum.org/EIPS/eip-7732"
#          - title: "Eth Magicians"
#            url: "https://ethereum-magicians.org/t/eip-7732-enshrined-proposer-builder-separation-epbs/19634"
      - name: ethpandaops/berlinterop-devnets
        namePrefix: berlinterop-
        displayName: Berlin Interop Devnets
        description: "Ephemeral devnets spun up exclusively for Berlin’s week of research and client interop—purpose-built to avoid disrupting ongoing Fusaka devnets."
        image: https://ethpandaops.io/img/berlinterop.jpg
      - name: ethpandaops/fusaka-devnets
        namePrefix: fusaka-
        displayName: Fusaka Devnets
        description: "Ethereum's Fusaka upgrade supercharges scalability with PeerDAS, boosts blob capacity, and slashes node overhead—paving the way for faster, cheaper L2s and smoother network ops."
        image: https://ethpandaops.io/img/fusaka.jpg
        links:
          - title: "EIP-7594: PeerDAS"
            url: "https://eips.ethereum.org/EIPS/eip-7594"
          - title: "ethresear.ch"
            url: "https://ethresear.ch/t/peerdas-a-simpler-das-approach-using-battle-tested-p2p-components/16541"
      - name: ethpandaops/eof-devnets
        namePrefix: eof-
        displayName: EOF Devnets
        description: "EOF is a new, versioned container format for EVM bytecode that separates code and data, validates contracts at deploy‑time, and unlocks cheaper, safer, future‑proof smart‑contract execution."
        image: https://ethpandaops.io/img/eof.jpg
        links:
          - title: "EIP-3540: EOF"
            url: "https://eips.ethereum.org/EIPS/eip-3540"
          - title: "EOF Overview"
            url: "https://notes.ethereum.org/@ipsilon/evm-object-format-overview"
      - name: ethpandaops/pectra-devnets
        namePrefix: pectra-
        displayName: Pectra Devnets
        description: "Pectra is the combined Prague‑Electra hard fork that ships 11 EIPs to streamline validator exits, sharpen wallet UX, and boost post‑Dencun scalability across both Ethereum’s execution and consensus layers."
        image: https://ethpandaops.io/img/pectra.jpg
        links:
          - title: "Pectra Roadmap"
            url: "https://ethereum.org/en/roadmap/pectra/"
      - name: ethpandaops/peerdas-devnets
        namePrefix: peerdas-
        displayName: PeerDAS Devnets
        description: "PeerDAS is a peer‑to‑peer data‑availability‑sampling protocol that lets beacon nodes verify blob data by grabbing random samples instead of the whole payload, slashing bandwidth and paving the way for full danksharding scale."
        image: https://ethpandaops.io/img/peerdas.jpg
        links:
          - title: "EIP-7594: PeerDAS"
            url: "https://eips.ethereum.org/EIPS/eip-7594"
          - title: "ethresear.ch"
            url: "https://ethresear.ch/t/peerdas-a-simpler-das-approach-using-battle-tested-p2p-components/16541"
      - name: ethpandaops/ssz-devnets
        namePrefix: ssz-
        displayName: SSZ Devnets
        description: "SSZ upgrade migrates execution‑layer blocks and transactions from legacy RLP to the Simple Serialize container format, unifying data structures with the consensus layer and enabling smaller, stateless proofs plus easier future extensions."
        image: https://ethpandaops.io/img/ssz.jpg
        links:
          - title: "EIP-7807: SSZ"
            url: "https://eips.ethereum.org/EIPS/eip-7807"
          - title: "SSZ Overview"
            url: "https://ethereum.org/en/developers/docs/data-structures-and-encoding/ssz/"
      - name: ethpandaops/nft-devnets
        namePrefix: nft-
        displayName: NFT Devnets
        description: "NFTs are purpose‑built Non‑Finality Testnets that deliberately drop finality to stress‑test clients and validators on detecting, diagnosing, and recovering an unstable chain."
        image: https://ethpandaops.io/img/nft.jpg
      - name: ethpandaops/perf-devnets
        namePrefix: perf-
        displayName: Perf Devnets
        description: "A specialized set of Ethereum testnets focused on stress-testing gas limits and evaluating EVM performance under extreme execution loads"
        image: https://ethpandaops.io/img/perf.jpg
      - name: ethpandaops/mekong-devnets
        namePrefix: mekong-
        displayName: Mekong Devnets
        description: "Mekong is a testing ground where anyone can confidently prepare for the Pectra upgrade, ensuring a smooth, non-stressed transition for the whole Ethereum ecosystem."
        image: https://ethpandaops.io/img/mekong.jpg
      - name: ethpandaops/dencun-devnets
        namePrefix: dencun-
        displayName: Dencun Devnets
        description: "The Dencun upgrade is a significant update to the Ethereum blockchain, aimed at enhancing scalability and efficiency, especially for Layer 2 (L2) rollups."
        image: https://ethpandaops.io/img/dencun.jpg

    # GitHub API token (via environment variable)
    token: ${GITHUB_TOKEN}

# Validator ranges configuration (optional)
validatorRanges:
  # Additional third-party validator sources
  #
  # Validator Range Distribution:
  # On testnets, validators are typically distributed across multiple organizations.
  # Each organization may number their validators locally starting from 0, but globally
  # they're assigned specific ranges to avoid conflicts.
  #
  # Example for fusaka-devnet-5:
  #   - ethpandaops:     0-50,912    (owned and operated by ethpandaops)
  #   - Reserved:    50,913-51,311    (400 validators reserved for Prysm, not yet deployed)
  #   - testinprod:  51,312-56,000    (assigned to testinprod/Sunny Side Labs)
  #
  # Since external organizations number their validators locally (e.g., testinprod uses 0-4,688),
  # we need to apply an offset to map their local ranges to the global validator numbering.
  #
  # rangeOffset: The value to add to all validator_start and validator_end values from this source
  #              to map them to their globally assigned range.
  additionalSources:
    fusaka-devnet-5:
      - url: https://raw.githubusercontent.com/testinprod-io/fusaka-devnets/refs/heads/main/ansible/inventories/devnet-5/inventory.ini
        name: testinprod
        rangeOffset: 51312  # Maps testinprod's local 0-4688 to global 51312-56000

# S3 storage configuration
storage:
  # S3 bucket name - environment variable example: ${S3_BUCKET_NAME}
  bucketName: ${S3_BUCKET_NAME}

  # S3 key (path) for the networks.json file
  key: networks.json

  # AWS region - environment variable example: ${AWS_REGION}
  region: ${AWS_REGION}

  # S3-compatible endpoint (for DigitalOcean Spaces)
  endpoint: https://ams3.digitaloceanspaces.com

  # Access credentials using environment variables
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}

  # Force path style addressing (for some S3-compatible services)
  forcePathStyle: true

  # Content type for the uploaded file
  contentType: application/json

  # Access control list for the uploaded file (REQUIRED for public access)
  acl: public-read

  # Retry configuration
  retryDuration: 5s
  maxRetries: 3
  backoffJitterPercent: 20
