# Cartographoor Service Configuration

# Logging configuration
logging:
  level: info

# Run once and exit
# runOnce: false

# Discovery configuration
discovery:
  # Discovery interval (default: 1h)
  interval: 1h
  
  # GitHub discovery configuration
  github:
    # List of repositories to check for networks
    repositories:
      # Example with a network name prefix (e.g. "devnet-4" becomes "dencun-devnet-4")
      - name: ethpandaops/dencun-devnets
        namePrefix: dencun-
    
    # GitHub API token (REQUIRED)
    # token: ghp_your_github_token

# S3 storage configuration
storage:
  # S3 bucket name - environment variable example: ${S3_BUCKET_NAME}
  bucketName: ethpandaops-networks
  
  # S3 key (path) for the networks.json file
  key: networks.json
  
  # AWS region - environment variable example: ${AWS_REGION}
  region: us-east-1
  
  # S3-compatible endpoint (optional, for non-AWS S3 implementations)
  # endpoint: https://s3.example.com
  
  # Access credentials using environment variables
  # accessKey: ${AWS_ACCESS_KEY_ID}
  # secretKey: ${AWS_SECRET_ACCESS_KEY}
  
  # Force path style addressing (for some S3-compatible services)
  # forcePathStyle: true
  
  # Disable SSL (not recommended for production)
  # disableSSL: false
  
  # Content type for the uploaded file
  contentType: application/json
  
  # Access control list for the uploaded file (optional)
  # acl: public-read
  
  # Retry configuration
  retryDuration: 5s
  maxRetries: 3
  backoffJitterPercent: 20