// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ethpandaops/cartographoor/pkg/client (interfaces: Provider)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/mock_provider.go github.com/ethpandaops/cartographoor/pkg/client Provider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	discovery "github.com/ethpandaops/cartographoor/pkg/discovery"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// GetActiveNetworks mocks base method.
func (m *MockProvider) GetActiveNetworks(ctx context.Context) (map[string]discovery.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveNetworks", ctx)
	ret0, _ := ret[0].(map[string]discovery.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveNetworks indicates an expected call of GetActiveNetworks.
func (mr *MockProviderMockRecorder) GetActiveNetworks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveNetworks", reflect.TypeOf((*MockProvider)(nil).GetActiveNetworks), ctx)
}

// GetClient mocks base method.
func (m *MockProvider) GetClient(ctx context.Context, name string) (discovery.ClientInfo, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", ctx, name)
	ret0, _ := ret[0].(discovery.ClientInfo)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetClient indicates an expected call of GetClient.
func (mr *MockProviderMockRecorder) GetClient(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockProvider)(nil).GetClient), ctx, name)
}

// GetClients mocks base method.
func (m *MockProvider) GetClients(ctx context.Context) (map[string]discovery.ClientInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClients", ctx)
	ret0, _ := ret[0].(map[string]discovery.ClientInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClients indicates an expected call of GetClients.
func (mr *MockProviderMockRecorder) GetClients(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClients", reflect.TypeOf((*MockProvider)(nil).GetClients), ctx)
}

// GetClientsByType mocks base method.
func (m *MockProvider) GetClientsByType(ctx context.Context, clientType string) (map[string]discovery.ClientInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientsByType", ctx, clientType)
	ret0, _ := ret[0].(map[string]discovery.ClientInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientsByType indicates an expected call of GetClientsByType.
func (mr *MockProviderMockRecorder) GetClientsByType(ctx, clientType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientsByType", reflect.TypeOf((*MockProvider)(nil).GetClientsByType), ctx, clientType)
}

// GetNetwork mocks base method.
func (m *MockProvider) GetNetwork(ctx context.Context, name string) (discovery.Network, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetwork", ctx, name)
	ret0, _ := ret[0].(discovery.Network)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetNetwork indicates an expected call of GetNetwork.
func (mr *MockProviderMockRecorder) GetNetwork(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetwork", reflect.TypeOf((*MockProvider)(nil).GetNetwork), ctx, name)
}

// GetNetworks mocks base method.
func (m *MockProvider) GetNetworks(ctx context.Context) (map[string]discovery.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworks", ctx)
	ret0, _ := ret[0].(map[string]discovery.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworks indicates an expected call of GetNetworks.
func (mr *MockProviderMockRecorder) GetNetworks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworks", reflect.TypeOf((*MockProvider)(nil).GetNetworks), ctx)
}

// NotifyChannel mocks base method.
func (m *MockProvider) NotifyChannel() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyChannel")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// NotifyChannel indicates an expected call of NotifyChannel.
func (mr *MockProviderMockRecorder) NotifyChannel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyChannel", reflect.TypeOf((*MockProvider)(nil).NotifyChannel))
}

// Ready mocks base method.
func (m *MockProvider) Ready() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ready")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Ready indicates an expected call of Ready.
func (mr *MockProviderMockRecorder) Ready() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ready", reflect.TypeOf((*MockProvider)(nil).Ready))
}

// Start mocks base method.
func (m *MockProvider) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockProviderMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockProvider)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockProvider) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockProviderMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockProvider)(nil).Stop))
}
