name: Validator Ranges Generation

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Manual trigger

jobs:
  generate-inventory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
          check-latest: true

      - name: Build Cartographoor
        run: |
          go build -o cartographoor ./cmd/cartographoor

      - name: Run Validator Ranges Generation
        run: |
          ./cartographoor validator-ranges --config=.github/config.production.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.CARTOGRAPHOOR_GITHUB_TOKEN }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
